name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.11'

      - run: python -m venv .venv
      - run: make install
      - run: ./.venv/bin/pip install -e .
      - run: make lint
      - run: make test
