name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.11'

      - run: pip install build
      - run: python -m build
      - run: ls -la dist
      - uses: pypa/gh-action-pypi-publish@release/v1
